Slince\Shopify\Manager\Inventory\InventoryLevel:
    properties:
        id:
            type: integer
        inventoryItemId:
            type: integer
        locationId:
            type: integer
        available:
            type: integer
        updatedAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        adminGraphqlApiId:
            type: string