Slince\Shopify\Manager\Collect\Collect:
    properties:
        id:
            type: integer
        collectionId:
            type: integer
        createdAt:
            type: DateTime<'Y-m-d\TH:i:sO'>
        updatedAt:
            type: DateTime<'Y-m-d\TH:i:sO'>
        featured:
            type: boolean
        position:
            type: string
        productId:
            type: integer
        sortValue:
            type: string

