Slince\Shopify\Manager\Product\Product:
    properties:
        bodyHtml:
            type: string
        handle:
            type: string
        id:
            type: integer
        images:
            type: array<Slince\Shopify\Manager\Product\ProductImage\Image>
        options:
            type: array<Slince\Shopify\Manager\Product\Option>
        productType:
            type: string
        publishedAt:
            type: DateTime<'Y-m-d\TH:i:sO'>
        publishedScope:
            type: string
        tags:
            type: string
        templateSuffix:
            type: string
        title:
            type: string
        createdAt:
            type: DateTime<'Y-m-d\TH:i:sO'>
        updatedAt:
            type: DateTime<'Y-m-d\TH:i:sO'>
        variants:
            type: array<Slince\Shopify\Manager\Product\ProductVariant\Variant>
        vendor:
            type: string
